### ISSUE TITLE
style scoped 속성이 CSS 선택자가 아닌 keyframes 이름에 Hash를 추가하는 문제.

### ISSUE THREAD

**Issue by ParkYoungWoong** [ParkYoungWoong/vue3-webpack-template#1]
## Issues

- style scoped 속성이 CSS 선택자가 아닌 keyframes 이름에 Hash를 추가하는 문제.

```scss
// Example..
.spinner-border[HASH] {
  // 생략..
  animation: $spinner-animation-speed linear infinite spinner-border-HASH;
}
```

## Solutions

- `@vue/compiler-sfc` 버전을 최신으로 수정할 것!
